from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 600)
        icon = QtGui.QIcon()
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)

        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 25)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_raw = QtWidgets.QLabel(self.groupBox)
        self.label_raw.setAutoFillBackground(False)
        self.label_raw.setText("")
        self.label_raw.setScaledContents(False)
        self.label_raw.setAlignment(QtCore.Qt.AlignCenter)
        self.label_raw.setObjectName("label_raw")
        self.horizontalLayout_2.addWidget(self.label_raw)
        self.label_result = QtWidgets.QLabel(self.groupBox)
        self.label_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result.setText("")
        self.label_result.setScaledContents(False)
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_2.addWidget(self.label_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(1, 10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)

        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background:transparent")
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setFlow(0)
        self.listWidget.setMaximumHeight(20)

        self.horizontalLayout_3.setStretch(0, 9)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setStyleSheet("background:#F5F5F5;border-color:#F5F5F5")
        self.SelModel = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icon/数据探索.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.SelModel.setIcon(icon1)
        self.SelModel.setObjectName("SelModel")
        self.SelFile = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.SelFile.setIcon(icon2)
        self.SelFile.setObjectName("SelFile")
        self.RunProgram = QtWidgets.QAction(MainWindow)
        self.RunProgram.setCheckable(True)
        self.RunProgram.setChecked(False)
        self.RunProgram.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icon/停止.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("./icon/暂停.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("./icon/停止.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.RunProgram.setIcon(icon3)
        self.RunProgram.setObjectName("RunProgram")
        self.cam_switch = QtWidgets.QAction(MainWindow)
        self.cam_switch.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icon/摄像头开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("./icon/摄像头关.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cam_switch.setIcon(icon4)
        self.cam_switch.setObjectName("cam_switch")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.toolBar.addAction(self.SelModel)
        self.toolBar.addAction(self.SelFile)
        self.toolBar.addAction(self.cam_switch)
        self.toolBar.addAction(self.RunProgram)
        self.toolBar.addWidget(self.horizontalSlider)

        self.verticalLayout.addWidget(self.listWidget)
        self.listWidget.setStyleSheet("background:#FFFFFF;  border-image:none; border: 1px solid #E4E4E4; border-radius: 2px;")
        self.centralwidget.setStyleSheet("background:#F5F5F5")
        self.groupBox.setStyleSheet("background:#FFFFFF")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YOLOv5 ver.6 GUI"))
        MainWindow.setWindowOpacity(1)
        self.label_2.setText(_translate("MainWindow", "Input Image"))
        self.label.setText(_translate("MainWindow", "Output Image"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.SelModel.setText(_translate("MainWindow", "Select Model"))
        self.SelModel.setToolTip(_translate("MainWindow", "Select Model"))
        self.SelFile.setText(_translate("MainWindow", "Select File"))
        self.SelFile.setToolTip(_translate("MainWindow", "Select File"))
        self.RunProgram.setText(_translate("MainWindow", "Run"))
        self.RunProgram.setToolTip(_translate("MainWindow", "Run"))
        self.cam_switch.setText(_translate("MainWindow", "Camera"))
        self.cam_switch.setToolTip(_translate("MainWindow", "Camera"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
